[package]
name = "upkg"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
chrono = "0.4"
regex = "1.10"
alpm = "4"
reqwest = { version = "0.12", features = ["blocking"] }
